package Interface.Conta;

import Banco.PessoaDAO;
import Controle.GerenciaCompra;
import Controle.GerenciaConta;
import Model.Fatura;
import Model.Pagamento;
import java.text.DecimalFormat;
import java.util.Iterator;
import javax.swing.JOptionPane;

public class PagarFatura extends javax.swing.JDialog {

    private PessoaDAO pDAO = new PessoaDAO();
    private GerenciaCompra gerenciaCompra = new GerenciaCompra();
    private GerenciaConta gerenciaConta = new GerenciaConta();
    private Fatura fatura;
    private int parcelaPendente;
    private int parcelasPagas;

    public PagarFatura(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public PagarFatura(javax.swing.JDialog parent, boolean modal, Fatura fatura) {
        super(parent, modal);

        this.fatura = fatura;
        this.parcelasPagas = parcelasPagas;
        initComponents();
        setLocationRelativeTo(null);
        btnPagar.setVisible(true);
        faturaPaga.setVisible(false);
        resetar();
        ShowsCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        faturaPaga = new javax.swing.JLabel();
        painelConsultarFatura = new javax.swing.JPanel();
        fundo7 = new javax.swing.JLabel();
        Painel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        valorparcela = new javax.swing.JLabel();
        Painel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Juros = new javax.swing.JLabel();
        Painel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        dataQuitacao = new javax.swing.JLabel();
        Painel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        codigoFatura = new javax.swing.JLabel();
        fundo13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fundo8 = new javax.swing.JLabel();
        Painel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        qtdParcelas = new javax.swing.JLabel();
        fundo12 = new javax.swing.JLabel();
        Painel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        parcelPag = new javax.swing.JLabel();
        closeIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        totalFatura = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPagarProxima = new javax.swing.JButton();
        btnPagarUltima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        faturaPaga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/faturaPaga.png"))); // NOI18N
        jPanel1.add(faturaPaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 210, 210));

        painelConsultarFatura.setBackground(new java.awt.Color(255, 255, 255));

        fundo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fundoRelatorio.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("VALOR PARCELA:");

        valorparcela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valorparcela.setForeground(new java.awt.Color(255, 0, 51));
        valorparcela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout Painel12Layout = new javax.swing.GroupLayout(Painel12);
        Painel12.setLayout(Painel12Layout);
        Painel12Layout.setHorizontalGroup(
            Painel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(valorparcela, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel12Layout.setVerticalGroup(
            Painel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(valorparcela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("JUROS:");

        Juros.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Juros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout Painel9Layout = new javax.swing.GroupLayout(Painel9);
        Painel9.setLayout(Painel9Layout);
        Painel9Layout.setHorizontalGroup(
            Painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(Juros, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel9Layout.setVerticalGroup(
            Painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel9Layout.createSequentialGroup()
                .addGroup(Painel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(Juros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));
        jLabel10.setText("DATA DE QUITAÇÃO:");

        dataQuitacao.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        dataQuitacao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout Painel8Layout = new javax.swing.GroupLayout(Painel8);
        Painel8.setLayout(Painel8Layout);
        Painel8Layout.setHorizontalGroup(
            Painel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(dataQuitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        Painel8Layout.setVerticalGroup(
            Painel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(dataQuitacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Painel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("CÓDIGO:");

        codigoFatura.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        codigoFatura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout Painel4Layout = new javax.swing.GroupLayout(Painel4);
        Painel4.setLayout(Painel4Layout);
        Painel4Layout.setHorizontalGroup(
            Painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigoFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Painel4Layout.setVerticalGroup(
            Painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel4Layout.createSequentialGroup()
                .addGroup(Painel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(codigoFatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fundo13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fundoRelatorio.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("DADOS DA FATURA");

        fundo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fundoRelatorio.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("QUANTIDADE DE PARCELAS: ");

        qtdParcelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qtdParcelas.setForeground(new java.awt.Color(255, 0, 51));
        qtdParcelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout Painel10Layout = new javax.swing.GroupLayout(Painel10);
        Painel10.setLayout(Painel10Layout);
        Painel10Layout.setHorizontalGroup(
            Painel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(47, 47, 47)
                .addComponent(qtdParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel10Layout.setVerticalGroup(
            Painel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel10Layout.createSequentialGroup()
                .addGroup(Painel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qtdParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        fundo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fundoRelatorio.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("PARCELAS PAGAS:");

        parcelPag.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        parcelPag.setForeground(new java.awt.Color(255, 0, 51));
        parcelPag.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout Painel11Layout = new javax.swing.GroupLayout(Painel11);
        Painel11.setLayout(Painel11Layout);
        Painel11Layout.setHorizontalGroup(
            Painel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(parcelPag, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel11Layout.setVerticalGroup(
            Painel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel11Layout.createSequentialGroup()
                .addGroup(Painel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(parcelPag, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelConsultarFaturaLayout = new javax.swing.GroupLayout(painelConsultarFatura);
        painelConsultarFatura.setLayout(painelConsultarFaturaLayout);
        painelConsultarFaturaLayout.setHorizontalGroup(
            painelConsultarFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultarFaturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelConsultarFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelConsultarFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelConsultarFaturaLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(220, 220, 220))
                        .addGroup(painelConsultarFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Painel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fundo13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(fundo7, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Painel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fundo8, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelConsultarFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Painel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Painel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Painel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fundo12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Painel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        painelConsultarFaturaLayout.setVerticalGroup(
            painelConsultarFaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsultarFaturaLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(fundo13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Painel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fundo8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(fundo7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fundo12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Painel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(painelConsultarFatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 630, 370));

        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-close-window-40.png"))); // NOI18N
        closeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
        });
        jPanel1.add(closeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 40, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULTA DE FATURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 300, -1));

        btnPagar.setBackground(new java.awt.Color(255, 255, 255));
        btnPagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N
        btnPagar.setMnemonic('S');
        btnPagar.setText("Pagar");
        btnPagar.setToolTipText("Salva os registros");
        btnPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagar.setFocusPainted(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 210, 40));

        totalFatura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalFatura.setForeground(new java.awt.Color(153, 0, 51));
        totalFatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(totalFatura, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(totalFatura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("R$");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 30, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOTAL: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 80, 40));

        btnPagarProxima.setBackground(new java.awt.Color(255, 255, 255));
        btnPagarProxima.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPagarProxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N
        btnPagarProxima.setMnemonic('S');
        btnPagarProxima.setText("Pagar Próxima Parcela");
        btnPagarProxima.setToolTipText("Salva os registros");
        btnPagarProxima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagarProxima.setFocusPainted(false);
        btnPagarProxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarProximaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagarProxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 210, 40));

        btnPagarUltima.setBackground(new java.awt.Color(255, 255, 255));
        btnPagarUltima.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPagarUltima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N
        btnPagarUltima.setMnemonic('S');
        btnPagarUltima.setText("Pagar Última Parcela");
        btnPagarUltima.setToolTipText("Salva os registros");
        btnPagarUltima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagarUltima.setFocusPainted(false);
        btnPagarUltima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarUltimaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagarUltima, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(rootPane, "Deseja Pagar a parcela?");

        if (JOptionPane.YES_OPTION == opcao) {

            gerenciaConta.pagarParcela(parcelaPendente, fatura);
            JOptionPane.showMessageDialog(rootPane, "Parcela paga com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        if (JOptionPane.NO_OPTION == opcao) {
            JOptionPane.showMessageDialog(rootPane, "A parcela não foi paga!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }

    }//GEN-LAST:event_btnPagarActionPerformed

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeIconMouseClicked

    private void btnPagarProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarProximaActionPerformed
         int opcao = JOptionPane.showConfirmDialog(rootPane, "Deseja Pagar a 2ª  parcela?");

        if (JOptionPane.YES_OPTION == opcao) {

            gerenciaConta.pagarParcela(parcelaPendente, fatura);
            JOptionPane.showMessageDialog(rootPane, "A 2ª parcela foi paga com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        if (JOptionPane.NO_OPTION == opcao) {
            JOptionPane.showMessageDialog(rootPane, "A parcela não foi paga!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btnPagarProximaActionPerformed

    private void btnPagarUltimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarUltimaActionPerformed
          int opcao = JOptionPane.showConfirmDialog(rootPane, "Deseja Pagar a 3ª parcela");

        if (JOptionPane.YES_OPTION == opcao) {

            gerenciaConta.pagarParcela(parcelaPendente, fatura);
            JOptionPane.showMessageDialog(rootPane, "A 3ª parcela foi paga com sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        if (JOptionPane.NO_OPTION == opcao) {
            JOptionPane.showMessageDialog(rootPane, "A parcela não foi paga!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_btnPagarUltimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarFatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PagarFatura dialog = new PagarFatura(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void ShowsCampos() {
        int parcelasPg = 0;
        Iterator i = fatura.getParcelas().iterator();
        while (i.hasNext()) {
            Pagamento pagamento = (Pagamento) i.next();
            if (pagamento.getStatus() > 0) {
                parcelasPg++;
            } else {
                parcelaPendente = pagamento.getId();
            }
        }
        codigoFatura.setText(Integer.toString(fatura.getId()));

        if (fatura.getDataQuitacao() != null) {
            dataQuitacao.setText(String.valueOf(fatura.getDataQuitacao()));
        } else {
            dataQuitacao.setText("Em aberto");
        }

        Juros.setText(Double.toString(fatura.getJuros()));
        qtdParcelas.setText(Integer.toString(fatura.getQuantParcelas()));
        Double total = fatura.getTotal();
        int parcelaAtual = parcelasPg + 1;
        int qtdParcelas = fatura.getQuantParcelas();
      
        switch(parcelaAtual){ 
            case 1:
                btnPagar.setVisible(true);
                break;
            case 2: 
                btnPagarProxima.setVisible(true);
                break;
            case 3: 
                btnPagarUltima.setVisible(true);
        }
        
        DecimalFormat df = new DecimalFormat("0.##");
         String dx;
         
        switch (qtdParcelas) {
            case 1:
                
                 dx = df.format(total);
                valorparcela.setText(dx);
                  
                
                break;
            case 2:
                
                 dx = df.format(total/2);
                valorparcela.setText(dx);
                break;
            case 3:
                dx = df.format(total/3);
                valorparcela.setText(dx);
                break;
        }
                
        totalFatura.setText(String.valueOf(fatura.getTotal()));
        parcelPag.setText(String.valueOf(parcelasPg));
        
        if (parcelasPg == fatura.getQuantParcelas()) {
            btnPagar.setVisible(false);
            faturaPaga.setVisible(true);
            
            
        }
        
        
        
    }
 private void resetar(){
     btnPagar.setVisible(false);
     btnPagarProxima.setVisible(false);
     btnPagarUltima.setVisible(false);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Juros;
    private javax.swing.JPanel Painel10;
    private javax.swing.JPanel Painel11;
    private javax.swing.JPanel Painel12;
    private javax.swing.JPanel Painel4;
    private javax.swing.JPanel Painel8;
    private javax.swing.JPanel Painel9;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnPagarProxima;
    private javax.swing.JButton btnPagarUltima;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JLabel codigoFatura;
    private javax.swing.JLabel dataQuitacao;
    private javax.swing.JLabel faturaPaga;
    private javax.swing.JLabel fundo12;
    private javax.swing.JLabel fundo13;
    private javax.swing.JLabel fundo7;
    private javax.swing.JLabel fundo8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel painelConsultarFatura;
    private javax.swing.JLabel parcelPag;
    private javax.swing.JLabel qtdParcelas;
    private javax.swing.JLabel totalFatura;
    private javax.swing.JLabel valorparcela;
    // End of variables declaration//GEN-END:variables
}
