/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Cliente;

import Banco.PessoaDAO;
import Interface.Endereco.AdicionarEndereco;
import Model.Endereco;
import Model.PessoaFisica;
import Model.PessoaJuridica;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class AlterarCliente extends javax.swing.JDialog {

    private PessoaJuridica pj;
    private PessoaFisica pf;
    private Endereco end = new Endereco();
    private ArrayList<Endereco> enderecos = new ArrayList<Endereco>();
    private PessoaDAO pDAO = new PessoaDAO();

    /**
     * Creates new form NewJDialog
     */
    public AlterarCliente(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        closeIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRb_Pfisica = new javax.swing.JRadioButton();
        jRbPessoaJuridica = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTf_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTF_cpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTF_NomeFantasia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTF_cnpj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTF_LimiteCredito = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTF_Logradouro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTF_numero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTF_Complemento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTF_Bairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTF_Municipio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTF_cep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jBtn_Salvar = new javax.swing.JButton();
        jCBoxUf = new javax.swing.JComboBox<>();
        jCBoxTipoEndereco = new javax.swing.JComboBox<>();
        jBtn_Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-close-window-40.png"))); // NOI18N
        closeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeIconMouseClicked(evt);
            }
        });
        jPanel1.add(closeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALTERAR CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 230, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(null);

        jRb_Pfisica.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(jRb_Pfisica);
        jRb_Pfisica.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRb_Pfisica.setForeground(new java.awt.Color(255, 255, 255));
        jRb_Pfisica.setMnemonic('F');
        jRb_Pfisica.setText("Pessoa Física");
        jRb_Pfisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRb_PfisicaActionPerformed(evt);
            }
        });
        jPanel2.add(jRb_Pfisica);
        jRb_Pfisica.setBounds(18, 33, 125, 27);

        jRbPessoaJuridica.setBackground(new java.awt.Color(0, 0, 51));
        buttonGroup1.add(jRbPessoaJuridica);
        jRbPessoaJuridica.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jRbPessoaJuridica.setForeground(new java.awt.Color(255, 255, 255));
        jRbPessoaJuridica.setMnemonic('J');
        jRbPessoaJuridica.setText("Pessoa Jurídica");
        jRbPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbPessoaJuridicaActionPerformed(evt);
            }
        });
        jPanel2.add(jRbPessoaJuridica);
        jRbPessoaJuridica.setBounds(208, 33, 150, 30);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 690, 80));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome*:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, 17));

        jTf_Nome.setEnabled(false);
        jPanel1.add(jTf_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 320, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF*:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jTF_cpf.setEnabled(false);
        jPanel1.add(jTF_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 320, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome Fantasia*:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 120, -1));

        jTF_NomeFantasia.setEnabled(false);
        jPanel1.add(jTF_NomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 300, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CNPJ*:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jTF_cnpj.setEnabled(false);
        jPanel1.add(jTF_cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 300, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Limite de Credito*:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, -1));

        jTF_LimiteCredito.setEnabled(false);
        jPanel1.add(jTF_LimiteCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 210, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logradouro*:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 100, -1));

        jTF_Logradouro.setEnabled(false);
        jPanel1.add(jTF_Logradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 430, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numero*:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 80, 20));

        jTF_numero.setEnabled(false);
        jPanel1.add(jTF_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 190, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Complemento:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 110, -1));

        jTF_Complemento.setEnabled(false);
        jPanel1.add(jTF_Complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 430, 30));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bairro*:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        jTF_Bairro.setEnabled(false);
        jPanel1.add(jTF_Bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 190, 30));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Municipio*:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 80, -1));

        jTF_Municipio.setEnabled(false);
        jPanel1.add(jTF_Municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 330, 30));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CEP*:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, 57, -1));

        jTF_cep.setEnabled(false);
        jPanel1.add(jTF_cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 190, 30));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("UF*:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 50, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo de endereço*:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 140, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Campos \"*\" sao obrigatorios");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 200, -1));

        jBtn_Salvar.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-ok-32.png"))); // NOI18N
        jBtn_Salvar.setMnemonic('A');
        jBtn_Salvar.setText("Alterar");
        jBtn_Salvar.setToolTipText("Salva os registros");
        jBtn_Salvar.setFocusPainted(false);
        jBtn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AlterarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 120, 40));

        jCBoxUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione -", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jCBoxUf.setEnabled(false);
        jCBoxUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxUfActionPerformed(evt);
            }
        });
        jPanel1.add(jCBoxUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 130, -1));

        jCBoxTipoEndereco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione -", "Residencial", "Comercial" }));
        jCBoxTipoEndereco.setEnabled(false);
        jPanel1.add(jCBoxTipoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 190, -1));

        jBtn_Limpar.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-apagar-32.png"))); // NOI18N
        jBtn_Limpar.setMnemonic('L');
        jBtn_Limpar.setText("Limpar");
        jBtn_Limpar.setToolTipText("Salva os registros");
        jBtn_Limpar.setFocusPainted(false);
        jBtn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_LimparActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_Limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeIconMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeIconMouseClicked

    private void jBtn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AlterarActionPerformed
        // TODO add your handling code here:
        if (jRbPessoaJuridica.isSelected()) {
           AlterarPessoaJuridica();
        } else if (jRb_Pfisica.isSelected()) {
            AlterarPessoaFisica();
        } else {
            JOptionPane.showMessageDialog(null, "Informe o tipo de cliente!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_AlterarActionPerformed

    private void jRb_PfisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRb_PfisicaActionPerformed
        desbloqueiaCampoFisica();
    }//GEN-LAST:event_jRb_PfisicaActionPerformed

    private void jRbPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbPessoaJuridicaActionPerformed
        desbloqueiaCampoJuridica();
    }//GEN-LAST:event_jRbPessoaJuridicaActionPerformed

    private void jCBoxUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBoxUfActionPerformed

    private void jBtn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_LimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlterarCliente dialog = new AlterarCliente(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    //jCBoxTipoEndereco.getItemAt(jCBoxTipoEndereco.getSelectedIndex())
   private void AlterarPessoaFisica() {
        if (!jTf_Nome.getText().isEmpty()) {
            if (!jTF_cpf.getText().isEmpty()) {
                if (!jTF_LimiteCredito.getText().isEmpty()) {
                    if (!jTF_Logradouro.getText().isEmpty()) {
                        if (!jTF_numero.getText().isEmpty()) {
                            if (!jTF_Bairro.getText().isEmpty()) {
                                if (!jTF_Municipio.getText().isEmpty()) {
                                    if (!jTF_cep.getText().isEmpty()) {
                                        if (!jCBoxUf.getItemAt(jCBoxUf.getSelectedIndex()).equals("- Selecione -")) {
                                            if (!jCBoxTipoEndereco.getItemAt(jCBoxTipoEndereco.getSelectedIndex()).equals("- Selecione -")) {
                                               int opcao= JOptionPane.showConfirmDialog(rootPane, "Deseja adicionar algum endereço ?");
                                                
                                                if (JOptionPane.YES_OPTION == opcao) {

                                                 AdicionarEndereco dialog = new AdicionarEndereco(new java.awt.Frame(), true);
                                                    dialog.setLocationRelativeTo(null);
                                                    dialog.setVisible(true);
                                                    //addEnderecosArray(dialog.getEnderecos());
                                                   
                                                    pf = new PessoaFisica(jTF_cpf.getText(), jTf_Nome.getText(), enderecos, Double.valueOf(jTF_LimiteCredito.getText()));

                                                }if (JOptionPane.NO_OPTION == opcao){

                                                    enderecos.add(capturarEndereco());
                                                    pf = new PessoaFisica(jTF_cpf.getText(), jTf_Nome.getText(), enderecos, Double.valueOf(jTF_LimiteCredito.getText()));
                                                    if (pDAO.inserirPessoaFisica(pf)) {
                                                        limparCampos();
                                                        JOptionPane.showMessageDialog(rootPane, "Cliente salvo com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                                                        this.dispose();
                                                    } else {
                                                        JOptionPane.showMessageDialog(rootPane, "Erro ao salvar cliente", "Mensagem", JOptionPane.ERROR_MESSAGE);

                                                    }

                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(rootPane, "Tipo de endereco e  obrigatorio!");
                                                jCBoxTipoEndereco.requestFocus();
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(rootPane, "UF e  obrigatorio!");
                                            jCBoxUf.requestFocus();
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(rootPane, "Campo CEP e  obrigatorio!");
                                        jTF_cep.requestFocus();
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "Campo Municipio e  obrigatorio!");
                                    jTF_Municipio.requestFocus();
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Campo Bairro e  obrigatorio!");
                                jTF_Bairro.requestFocus();
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Campo Numero e obrigatorio!");
                            jTF_numero.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Campo Logradouro e obrigatorio!");
                        jTF_Logradouro.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Campo Limite de credito e obrigatorio!");
                    jTF_LimiteCredito.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Campo CPF e obrigatorio!");
                jTF_cpf.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Campo Nome e obrigatorio!");
            jTf_Nome.requestFocus();
        }
    }
    private void AlterarPessoaJuridica() {
        
        if (!jTF_cnpj.getText().isEmpty()) {
            if (!jTf_Nome.getText().isEmpty()) {
                if (!jTF_NomeFantasia.getText().isEmpty()) {
                    if (!jTF_LimiteCredito.getText().isEmpty()) {
                        if (!jTF_Logradouro.getText().isEmpty()) {
                            if (!jTF_numero.getText().isEmpty()) {
                                if (!jTF_Bairro.getText().isEmpty()) {
                                    if (!jTF_Municipio.getText().isEmpty()) {
                                        if (!jTF_cep.getText().isEmpty()) {
                                            if (!jCBoxUf.getItemAt(jCBoxUf.getSelectedIndex()).equals("- Selecione -")) {
                                                if (!jCBoxTipoEndereco.getItemAt(jCBoxTipoEndereco.getSelectedIndex()).equals("- Selecione -")) {
                                                    int opcao = JOptionPane.showConfirmDialog(rootPane, "Deseja adicionar algum endereço ?");
                                                    if (JOptionPane.YES_OPTION == opcao) {
                                                        
                                                        AdicionarEndereco dialog = new AdicionarEndereco(new java.awt.Frame(), true);
                                                        dialog.setLocationRelativeTo(null);
                                                        dialog.setVisible(true);
                                                        
                                                        addEnderecosArray(dialog.getEnderecos());
                                                        
                                                        pj = new PessoaJuridica(jTF_NomeFantasia.getText(), jTF_cnpj.getText(), jTf_Nome.getText(), enderecos, Double.parseDouble(jTF_LimiteCredito.getText()));
                                                        
                                                        if (pDAO.inserirPessoaJuridica(pj)) {
                                                            limparCampos();
                                                            JOptionPane.showMessageDialog(rootPane, "Cliente salvo com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                                                            enderecos = null;
                                                            this.dispose();
                                                        } else {
                                                            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar cliente", "Mensagem", JOptionPane.ERROR_MESSAGE);
                                                            
                                                        }
                                                        
                                                    } else if (JOptionPane.NO_OPTION == opcao) {
                                                        enderecos.add(capturarEndereco());
                                                        pj = new PessoaJuridica(jTF_NomeFantasia.getText(), jTF_cnpj.getText(), jTf_Nome.getText(), enderecos, Double.parseDouble(jTF_LimiteCredito.getText()));
                                                        if (pDAO.inserirPessoaJuridica(pj)) {
                                                            limparCampos();
                                                            JOptionPane.showMessageDialog(rootPane, "Cliente salvo com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                                                            enderecos = null;
                                                            this.dispose();
                                                        } else {
                                                            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar cliente", "Mensagem", JOptionPane.ERROR_MESSAGE);
                                                            
                                                        }
                                                        
                                                    }
                                                } else {
                                                    JOptionPane.showMessageDialog(rootPane, "Tipo de endereco e  obrigatorio!");
                                                    jCBoxTipoEndereco.requestFocus();
                                                }
                                            } else {
                                                JOptionPane.showMessageDialog(rootPane, "UF e  obrigatorio!");
                                                jCBoxUf.requestFocus();
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(rootPane, "Campo CEP e  obrigatorio!");
                                            jTF_cep.requestFocus();
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(rootPane, "Campo Municipio e  obrigatorio!");
                                        jTF_Municipio.requestFocus();
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "Campo Bairro e  obrigatorio!");
                                    jTF_Bairro.requestFocus();
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Campo Numero e obrigatorio!");
                                jTF_numero.requestFocus();
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Campo Logradouro e obrigatorio!");
                            jTF_Logradouro.requestFocus();
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Campo Limite de credito e obrigatorio!");
                        jTF_LimiteCredito.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Campo Nome fantasia e obrigatorio!");
                    jTF_NomeFantasia.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Campo Nome e obrigatorio!");
                jTf_Nome.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Campo CNPJ e obrigatorio!");
            jTF_cnpj.requestFocus();
        }
        
    }
   
    private void desbloqueiaCampoFisica() {
        jTF_Bairro.setEnabled(true);
        jTF_Complemento.setEnabled(true);
        jTF_LimiteCredito.setEnabled(true);
        jTF_Logradouro.setEnabled(true);
        jTF_Municipio.setEnabled(true);
        jTF_NomeFantasia.setText(null);
        jTF_NomeFantasia.setEnabled(false);
        jCBoxTipoEndereco.setEnabled(true);
        jTF_cep.setEnabled(true);
        jTF_cnpj.setText(null);
        jTF_cnpj.setEnabled(false);
        jTF_cpf.setEnabled(true);
        jTF_numero.setEnabled(true);
        jTf_Nome.setEnabled(true);
        jCBoxUf.setEnabled(true);
    }

    private void desbloqueiaCampoJuridica() {
        jTF_Bairro.setEnabled(true);
        jTF_Complemento.setEnabled(true);
        jTF_LimiteCredito.setEnabled(true);
        jTF_Logradouro.setEnabled(true);
        jTF_Municipio.setEnabled(true);
        jTF_NomeFantasia.setEnabled(true);
        jTF_cep.setEnabled(true);
        jTF_cnpj.setEnabled(true);
        jTF_cpf.setText(null);
        jTF_cpf.setEnabled(false);
        jTF_numero.setEnabled(true);
        jTf_Nome.setEnabled(true);
        jCBoxTipoEndereco.setEnabled(true);
        jCBoxUf.setEnabled(true);
    }

    private void limparCampos() {

        jTF_Bairro.setText(null);
        jTF_Complemento.setText(null);
        jTF_LimiteCredito.setText(null);
        jTF_Logradouro.setText(null);
        jTF_Municipio.setText(null);
        jTF_NomeFantasia.setText(null);
        jCBoxTipoEndereco.setSelectedIndex(0);
        jTF_cep.setText(null);
        jTF_cnpj.setText(null);
        jTF_cpf.setText(null);
        jTF_numero.setText(null);
        jTf_Nome.setText(null);
        jCBoxUf.setSelectedIndex(0);
    }

    private Endereco capturarEndereco() {
        end.setLogradouro(jTF_Logradouro.getText());
        end.setNumero(Integer.parseInt(jTF_numero.getText()));
        end.setBairro(jTF_Bairro.getText());
        end.setMunicipio(jTF_Municipio.getText());
        end.setComplemento(jTF_Complemento.getText());
        end.setCep(Integer.parseInt(jTF_cep.getText()));
        end.setEstado(jCBoxUf.getItemAt(jCBoxUf.getSelectedIndex()));
        if (jCBoxTipoEndereco.getItemAt(jCBoxTipoEndereco.getSelectedIndex()).equals("Residencial")) {
            end.setTipoEndereco(1);
        } else {
            end.setTipoEndereco(2);
        }
        return end;
    }
    private void addEnderecosArray(ArrayList<Endereco> add){
        enderecos= add;
        enderecos.add(capturarEndereco());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel closeIcon;
    private javax.swing.JButton jBtn_Limpar;
    private javax.swing.JButton jBtn_Salvar;
    private javax.swing.JComboBox<String> jCBoxTipoEndereco;
    private javax.swing.JComboBox<String> jCBoxUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRbPessoaJuridica;
    private javax.swing.JRadioButton jRb_Pfisica;
    private javax.swing.JTextField jTF_Bairro;
    private javax.swing.JTextField jTF_Complemento;
    private javax.swing.JTextField jTF_LimiteCredito;
    private javax.swing.JTextField jTF_Logradouro;
    private javax.swing.JTextField jTF_Municipio;
    private javax.swing.JTextField jTF_NomeFantasia;
    private javax.swing.JTextField jTF_cep;
    private javax.swing.JTextField jTF_cnpj;
    private javax.swing.JTextField jTF_cpf;
    private javax.swing.JTextField jTF_numero;
    private javax.swing.JTextField jTf_Nome;
    // End of variables declaration//GEN-END:variables
}
